server:
  port: 8082

spring:
  application:
    name: identity-access-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/iam}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_POOL_MAX:10}
      minimum-idle: ${SPRING_DATASOURCE_POOL_MIN:2}
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.kevdev.iam: DEBUG

ias:
  jwt:
    issuer: ${IAS_JWT_ISSUER:iamauth}
    secret:
      b64: ${IAS_JWT_SECRET_B64}
    access-ttl: ${IAS_ACCESS_TOKEN_TTL:PT15M}
    refresh-ttl: ${IAS_REFRESH_TOKEN_TTL:P30D}
  refresh:
    ttl: ${IAS_REFRESH_TOKEN_TTL:P30D}

