spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/iam
    username: postgres
    password: postgres

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operationsSorter: alpha
    tagsSorter: alpha

logging:
  level:
    org.springframework.security: DEBUG
    com.kevdev.iam: DEBUG

