server:
  port: 8082

spring:
  application:
    name: identity-access-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/iam}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_POOL_MAX:10}
      minimum-idle: ${SPRING_DATASOURCE_POOL_MIN:2}
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.kevdev.iam: DEBUG

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

ias:
  jwt:
    issuer: ${IAS_JWT_ISSUER:iamauth}
    access-ttl-minutes: ${IAS_JWT_ACCESS_TTL_MINUTES:15}
    secret:
      b64: ${IAS_JWT_SECRET_B64}
  refresh:
    ttl: ${IAS_REFRESH_TTL:30d}

